### ISSUE TITLE
Password revealed by preedit in Terminal

### ISSUE THREAD

**Issue by schuetzer** [fcitx/fcitx-unikey#11]
With `fcitx-unikey` turned on, whenever I type my password into a terminal (e.g. using `sudo` with a command) preedit will reveal my input partially or entirely (see attached image) until I hit Space or Enter. Note that it doesn't reveal the password input elsewhere (e.g. with `kdesudo` or `gksu` etc.).

![password](https://cloud.githubusercontent.com/assets/15033778/14790572/15254d3c-0b12-11e6-8e6a-ea0d4eb71da9.png) 

Normally this isn't a big issue when I remember to switch to another input methods like German or English. However, for security reasons, it shouldn't have revealed the password in first place.

My current system: 
OS: Kubuntu 16.04
Kernel: x86_64 Linux 4.4.0-21-generic
Shell: bash 4.3.42
DE: KDE5
WM: KWin
fcitx 1:4.2.9.1-1ubuntu1
fcitx-unikey 0.2.4-1

**Comment by yuyichao** [comment]
I believe this is limited by the terminal interface.
