### ISSUE TITLE
Error when typing words beginning with "qu" and "gi"

### ISSUE THREAD

**Issue by PyGeek03** [fcitx/fcitx-unikey#13]
Hi, I really appreciate your work on this piece of software, which is truly essential for a Vietnamese Xubuntu user like me.  Just 1 small problem though: When I try to type any words beginning with "qu" (e.g. "quà", "quẻ", "quạu quọ"...), the accent keep being assigned to the character "u" instead of the correct vowel in the word (e.g. "qùa", "qủe", "quaụ qụo"...). The problem persists whether I enable "Use oà, _uý (instead of òa, uý) or not. Can you fix it, please? Or is there a workaround for this?

**Comment by PyGeek03** [comment]
Just like the issue with "gi" that I have opened after this, a quick way to fix this problem is to consider "qu" as a consonant unit, just like "gh", "ch" or "th".

**Comment by wengxt** [comment]
I'd like to help, but just let you know I don't read Vietnamese, and it is a port based on scim-unikey. Possibly it's an old bug carried from scim-unikey.

Could you elaborate in more details on what's the key you type and what's the expected behavior and actual behavior?

**Comment by wengxt** [comment]
Btw, it would be helpful if you can point me to some reference in English for people don't know about Vietnamese to read.

**Comment by PyGeek03** [comment]
Sorry for the late reply. I cannot find such a reference, however I'll try my best to describe the keys typed, the expected behavior and the actual behavior. Btw, I'm using VNI style, so the number keys 1, 2, 3, 4, 5 are for adding accents on vowels, i.e. 'a' +'1' = 'á', 'e' + '2' = 'è', 'u' + '3' = 'ủ', 'i' + '4' = 'ĩ', 'o' + '5' = 'ọ'.

1) The accent is placed on the 'u' in the 'qu' consonant unit, instead of the real vowel that comes after 'qu':
- Typed: 'q'+'u'+'a'+'2'
- Expect: 'quà'
- Actual: 'qùa'

2) The accent is placed on the 'u' in the 'qu' consonant unit, instead of the first vowel in the vowel unit that comes after 'qu':
- Typed: 'q' + 'u' + 'a' + '5' + 'u'
- Expect: 'quạu'
- Actual: 'qụau'

Btw, while typing for this example, I've discovered yet another issue with the placing of accents over vowels in a vowel unit, such as 'au'. I'll file another separate issue.

**Comment by wengxt** [comment]
Ok, can you confirm this only happens in firefox?

Looks like this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1182596

**Comment by wengxt** [comment]
I think you can workaround it by enable Macro for now.

**Comment by PyGeek03** [comment]
OK I'll try that. I changed the title because it seems that the issue happens for "gi", too.

**Comment by PyGeek03** [comment]
The issue does not happen in LibreOffice and Vivaldi, and when I enable Macro, the issue does not happen in Firefox. It seems like I've been wasting your time, sorry.

**Comment by PyGeek03** [comment]
Btw, can you explain what does the option "Enable Macro" do? Thanks beforehand.

**Comment by wengxt** [comment]
There's a functionality that let you to type some word and replace it with another one, it's the same idea as C's macro https://gcc.gnu.org/onlinedocs/cpp/Macros.html .

fcitx-unikey comes with an editor for it, you can launch it from configtool or via following commands.

/usr/lib/fcitx/libexec/fcitx-qt-gui-wrapper unikey/macro
