### ISSUE TITLE
Error when typing words beginning with "gi"

### ISSUE THREAD

**Issue by PyGeek03** [fcitx/fcitx-unikey#14]
When I try to type the word "giây" (which means "second", or 1/60 of a minute in Vietnamese), it interpret my typed word as "giay6" (if I type "6" after "y") or "gia6y" (if I type "6" after "a"). I'm using VNI, by the way. The problem doesn't change even when I disable  "Use oà, _uý (instead of òa, úy)".
Is there a way to fix this?

**Comment by PyGeek03** [comment]
Btw, I think the quickest way to fix this is to require it to intepret "gi" as a unit of consonant (which is true in Vietnamese grammar), because I also encounter issues with similar words beginning with "gi". For example, when I type "giáo" with "1" being typed after "o", it puts the consonant on the character "o", creating "giaó"; if I type "1" after "a", it creates "gíao". This issue exists whether  "Use oà, _uý (instead of òa, úy)" is enabled or not.

**Comment by wengxt** [comment]
See my comment to #13 and provide more details, thanks!

**Comment by PyGeek03** [comment]
Sorry for my poor description. I forgot to mention that I'm using VNI style, where 'a' + '6' = 'â'.

1) Typed: 'g' + 'i' + 'a' + 'y' + '6'
- Expected: 'giây'
- Actual: 'giay6'

2) Typed: 'g' + 'i' + 'a' + '6' + 'u'
- Expected: 'giâu'
- Actual: 'gia6u'

My earlier suggestion is based on the observation that while the actual behavior of the consonant units 'kh', 'th', 'ch' and 'qu' match the expected behavior (i.e. placing '^' on 'a' correctly when '6' is typed), only the consonant unit 'gi' fails to perform this. 

Also, when typing the consonant units 'kh', 'th' and  'ch', the underline only appears under the succeeding vowels (i.e. when I type the word 'khan', the underline only appears under 'an'), but when typing the consonants units 'gi' and 'qu', the underline includes the characters 'i' and 'u' (i.e. when I type the words 'giau' and 'quy', the underline appears under 'iau' and 'uy'). 

Therefore, I suppose that by simply assigning 'gi' and 'qu' into the same class as 'kh', 'th' and 'ch', this issue and #13 will be fixed quickly.

**Comment by wengxt** [comment]
Close as a duplicate as #13
