### ISSUE TITLE
Cannot install fcitx-unikey via apt-get

### ISSUE THREAD

**Issue by SaitDev** [fcitx/fcitx-unikey#15]
I run the command `apt-get install fcitx-unikey` on Kali linux but it say `Package fcitx-unikey is not available`
How can I install fcitx-unikey?

**Comment by yuyichao** [comment]
The package seems to exist on new enough version of debian https://packages.debian.org/jessie/utils/fcitx-unikey . It's a distribution issue if you can't find it in the repo/need to find out how to add/enable/sync the right repo.
