### ISSUE TITLE
Unikey not work

### ISSUE THREAD

**Issue by sonbui00** [fcitx/fcitx-unikey#4]
I have a issue with fcitx-unikey:
(ERROR-4883 /build/buildd/fcitx-unikey-0.2.2/src/unikey-im.cpp:503) Load Config Description File fcitx-unikey.desc Erorr, Please Check your install.

**Comment by longthanhtran** [comment]
I think the issue still persists as I tried with ubuntu package by today, same error with unikey-im.cpp:503 Load Config Description File fcitx-unikey.desc Erorr, Please check your install.

**Comment by wengxt** [comment]
The bug is already fixed upstream, please ask your packager to update.

**Comment by longthanhtran** [comment]
Thanks for your update, then I will inform Ubuntu packaging team.
