### ISSUE TITLE
cannot enter "giow"

### ISSUE THREAD

**Issue by s8dtvt** [fcitx/fcitx-unikey#6]
It cannot input: "ơ, ô" following "gi-".
Example: instead of "giống, giờ", it show: "gioongs, giow"

**Comment by wengxt** [comment]
Cannot reproduce.

With telex, if I type gioongs, output is giống.

Are you sure the output mode is unicode instead of something else?

**Comment by s8dtvt** [comment]
ah, it only occure with firefox: gioongs
i use telex with output mode is unicode, thanks

**Comment by wengxt** [comment]
I did test it in firefox and it seems fine. What's the version of
fcitx-unikey?

Is it a specific page that triggers this problem? Or you just can't use any
input method in firefox?

**Comment by s8dtvt** [comment]
I use fcitx-unikey-0.2.4-1 + firefox 40.0.3 + cinnamon DE on archlinux.
it trigger with all input of firefox include address bar, search bar.

**Comment by wengxt** [comment]
Can you run fcitx-diagnose and paste the output?

**Comment by s8dtvt** [comment]
here is output of fcitx-diagnose:
# System Info:
1.  `uname -a`:

        Linux decon 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        ID=arch
        PRETTY_NAME="Arch Linux"
        ANSI_COLOR="0;36"
        HOME_URL="https://www.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"

5.  Desktop Environment:

    Desktop environment is `gnome3`.

6.  Bash Version:

        BASH_VERSION='4.3.39(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc104", "us", "", ""

3.  Locale:

    1.  All locale:

            C
            en_US.utf8
            POSIX
            vi_VN
            vi_VN.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/duclong

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/duclong/.config`).

    3.  Fcitx Settings Directory:

        Current fcitx settings directory is `~/.config/fcitx` (`/home/duclong/.config/fcitx`).

5.  Current user:

    The script is run as duclong (1000).

# Fcitx State:
1.  executable:

    Found fcitx at `/usr/bin/fcitx`.

2.  version:

    Fcitx version: `4.2.9`

3.  process:

    Found 2 fcitx processes:

          809 fcitx
         2534 fcitx-dbus-watc

4.  `fcitx-remote`:

    `fcitx-remote` works properly.

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx-configtool at `/usr/bin/fcitx-configtool`.

2.  Config GUI for gtk2:

    **Config GUI for gtk2 not found.**

3.  Config GUI for gtk3:

    Found `fcitx-config-gtk3` at `/usr/bin/fcitx-config-gtk3`.

4.  Config GUI for kde:

    **`kcmshell4` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:
    Found fcitx qt module: `/usr/lib/fcitx/qt/libfcitx-quickphrase-editor.so`.
    Found fcitx im module for Qt5: `/usr/lib/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    Found fcitx im module for Qt4: `/usr/lib/qt4/plugins/inputmethods/qtim-fcitx.so`.

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.28` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.28

        Found fcitx im modules for gtk `2.24.28`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

        Found `gtk-query-immodules` for gtk `2.24.28` at `/usr/bin/gtk-query-immodules-2.0-32`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0-32 from gtk+-2.24.28

        **Failed to find fcitx in the output of `/usr/bin/gtk-query-immodules-2.0-32`**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.16.6` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.16.6

        Found fcitx im modules for gtk `3.16.6`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.28` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.28

        Found fcitx im modules for gtk `2.24.28`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

        Found immodules cache for gtk `2.24.28` at `/usr/lib32/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by usr/bin/gtk-query-immodules-2.0-32 from gtk+-2.24.28

        **Failed to find fcitx in immodule cache at `/usr/lib32/gtk-2.0/2.10.0/immodules.cache`**

    2.  gtk 3:

        Found immodules cache for gtk `3.16.6` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by usr/bin/gtk-query-immodules-3.0 from gtk+-3.16.6

        Found fcitx im modules for gtk `3.16.6`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx addon config directory: `/usr/share/fcitx/addon`.

2.  Addon List:

    1.  Found 26 enabled addons:

            fcitx-autoeng
            fcitx-chttrans
            fcitx-classic-ui
            fcitx-clipboard
            fcitx-dbus
            fcitx-freedesktop-notify
            fcitx-fullwidth-char
            fcitx-imselector
            fcitx-ipc
            fcitx-keyboard
            fcitx-kimpanel-ui
            fcitx-notificationitem
            fcitx-pinyin
            fcitx-pinyin-enhance
            fcitx-punc
            fcitx-quickphrase
            fcitx-remote
            fcitx-spell
            fcitx-table
            fcitx-unicode
            fcitx-unikey
            fcitx-vk
            fcitx-x11
            fcitx-xim
            fcitx-xkb
            fcitx-xkbdbus

    2.  Found 1 disabled addons:

            fcitx-qw

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        fcitx-classic-ui
        fcitx-kimpanel-ui

## Input Methods:
1.  Found 2 enabled input methods:

        fcitx-keyboard-us
        unikey

2.  Default input methods:

    You have a keyboard input method "fcitx-keyboard-us" correctly added as your default input method.

# Log:
1.  `date`:

        Sun Sep  6 12:57:38 ICT 2015

2.  `~/.config/fcitx/log/`:

        total 0

3.  `~/.config/fcitx/log/crash.log`:

    `~/.config/fcitx/log/crash.log` not found.

**Comment by wengxt** [comment]
Are you sure that fcitx is working with your gtk application? (Ctrl + space can change the state of fcitx in firefox)

If not, does following command help?
 gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule':<'fcitx'>}"

**Comment by s8dtvt** [comment]
yes, I can input other: đá, đấm, tưởng tượng, but not with "gi-" and "ô,ơ": gioo, giow
Can I give any information futher?

**Comment by s8dtvt** [comment]
and when I run command you give me above, it show:
decon ~ $  gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule':<'fcitx'>}"
No such schema 'org.gnome.settings-daemon.plugins.xsettings'

**Comment by wengxt** [comment]
Interesting.... is "gioongs" underlined when you are typing them?

**Comment by s8dtvt** [comment]
yes, it is.

**Comment by s8dtvt** [comment]
![screenshot from 2015-09-06 16-38-53](https://cloud.githubusercontent.com/assets/13790288/9703721/2cb96612-54b6-11e5-919b-ca6a72526ee3.png)

**Comment by wengxt** [comment]
Looks like the actual issue is that spellcheck is enabled and firefox is too eager to reset the input method state (https://bugzilla.mozilla.org/show_bug.cgi?id=1182596). Probably disable spellcheck by default is better option for fcitx-unikey.

Either disable spellcheck or enable macro in configuration may workaround it.

**Comment by s8dtvt** [comment]
Enable macro in config make it work normal.
Thanks u.
