### ISSUE TITLE
lỗｉ　khｉ　nhậｐ　tｉếｎｇ　vｉệｔ　trｏｎｇ　ｕｂｕｎｔｕ　14．04

### ISSUE THREAD

**Issue by ghost** [fcitx/fcitx-unikey#7]
bｕｉｌｄ　và　càｉ　đặｔ　xｏｎｇ　thì　khｉ　mìｎｈ　gõ　tｉếｎｇ　vｉệｔ　nó　rａ　thàｎｈ　thế　nàｙ．　Mìｎｈ　thử　tｅｓｔ　trｏｎｇ　lｉｂｒｅ　ｏｆｆｉｃｅ　thì　nó　sử　ｄụｎｇ　fｏｎｔ　Droid Sans Fallback　chứ　khôｎｇ　phảｉ　fｏｎｔ　củａ　ô　nhậｐ　lｉệｕ．　
Nhậｐ　ở　bấｔ　kỳ　ô　nhậｐ　lｉệｕ　nàｏ　cũｎｇ　đềｕ　rａ　thế　nàｙ
Mｏｎｇ　bạｎ　sửａ　sớｍ　lỗｉ　nàｙ．

**Comment by wengxt** [comment]
Hi, can you explain your issue in English? Thanks!

**Comment by justintv90** [comment]
Hey @wengxt , he meant " After buiding and installing Fcitx-unikey, His Vietnamese output like this at everywhere (there are spaces among characters) . He did try in Libre Office but the font be changed to Droid Sans Fallback instead of his custom font in Fcitx. He hope you can fix this issue soon.

**Comment by wengxt** [comment]
Hi @ghost, I think you enabled full width character in fcitx. Check the crescent/full-moon-like icon on the fcitx's panel. Click on the icon to make the icon looks like crescent moon and go back to normal half width input mode.
