### ISSUE TITLE
How to uninstall fxitx-unikey?

### ISSUE THREAD

**Issue by caoanhhao** [fcitx/fcitx-unikey#9]
i edit source and reinstall. it has no change.
so i want remove and install.
PS: i want to have a option "hide/show preedit dialog"

**Comment by wengxt** [comment]
You'd make sure you installed to the correct place, with -DCMAKE_INSTAL_PREFIX=/path/to/install

Check where the all other fcitx addon installs via your package manager or something else.
overwritten install should work, so you must have install it to the wrong place.

**Comment by caoanhhao** [comment]
thank for your anwser. i reinstall and LOGOUT then it has change.

**Comment by wengxt** [comment]
If the old fcitx-unikey is already loaded, you need to restart fcitx to make the new version work.
